export enum EstadoEnum {
    AC = "AC",
    AL = "AL",
    AP = "AP",
    AM = "AM",
    BA = "BA",
    CE = "CE",
    DF = "DF",
    ES = "ES",
    GO = "GO",
    MA = "MA",
    MT = "MT",
    MS = "MS",
    MG = "MG",
    PA = "PA",
    PB = "PB",
    PR = "PR",
    PE = "PE",
    PI = "PI",
    RJ = "RJ",
    RN = "RN",
    RS = "RS",
    RO = "RO",
    RR = "RR",
    SC = "SC",
    SP = "SP",
    SE = "SE",
    TO = "TO"
}


export const EstadoEnumLabelMapping: Record<EstadoEnum, any> = {
    [EstadoEnum.AC]: "AC",
    [EstadoEnum.AL]: "AL",
    [EstadoEnum.AP]: "AP",
    [EstadoEnum.AM]: "AM",
    [EstadoEnum.BA]: "BA",
    [EstadoEnum.CE]: "CE",
    [EstadoEnum.DF]: "DF",
    [EstadoEnum.ES]: "ES",
    [EstadoEnum.GO]: "GO",
    [EstadoEnum.MA]: "MA",
    [EstadoEnum.MT]: "MT",
    [EstadoEnum.MS]: "MS",
    [EstadoEnum.MG]: "MG",
    [EstadoEnum.PA]: "PA",
    [EstadoEnum.PB]: "PB",
    [EstadoEnum.PR]: "PR",
    [EstadoEnum.PE]: "PE",
    [EstadoEnum.PI]: "PI",
    [EstadoEnum.RJ]: "RJ",
    [EstadoEnum.RN]: "RN",
    [EstadoEnum.RS]: "RS",
    [EstadoEnum.RO]: "RO",
    [EstadoEnum.RR]: "RR",
    [EstadoEnum.SC]: "SC",
    [EstadoEnum.SP]: "SP",
    [EstadoEnum.SE]: "SE",
    [EstadoEnum.TO]: "TO"
};
